### ISSUE TITLE
Are collection matchers work with objects?

### ISSUE THREAD

**Issue by pyrsmk** [icy-arctic-fox/spectator#16]
I have this test that fails:

```cr
let(nodes) do
  [
    Node.new("<div></div>"),
    Node.new("<div></div>"),
    Node.new("<div></div>")
  ]
end

it "contains valid nodes" do
  expect(described_class.new(nodes).to_a).to contain_exactly nodes
end
```

There the output:

```
Failures:

  1) Katana::Html::NodeCollection#initialize contains the passed elements
     Failure: (described_class.new(nodes)).to_a does not contain exactly {nodes}

       expected: [[Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693f00 children=[#<XML::Element:0x10c685e00 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693e40 children=[#<XML::Element:0x10c685d80 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693d80 children=[#<XML::Element:0x10c685d00 name="div">]>)]]
         actual: [Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693f00 children=[#<XML::Element:0x10c685e00 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693e40 children=[#<XML::Element:0x10c685d80 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693d80 children=[#<XML::Element:0x10c685d00 name="div">]>)]
        missing: [Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693f00 children=[#<XML::Element:0x10c685e00 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693e40 children=[#<XML::Element:0x10c685d80 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693d80 children=[#<XML::Element:0x10c685d00 name="div">]>)]
          extra: [Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693f00 children=[#<XML::Element:0x10c685e00 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693e40 children=[#<XML::Element:0x10c685d80 name="div">]>), Katana::Html::Node(@is_text=false, @origin=#<XML::HTMLDocument:0x10c693d80 children=[#<XML::Element:0x10c685d00 name="div">]>)]

```

It seems the matcher cannot match the objects and for the test to pass, I need to write it like this:

```cr
it "contains valid nodes" do
  described_class.new(nodes).to_a.each_with_index do |node, i|
    expect(node).to eq nodes[i]
  end
end
```
