### ISSUE TITLE
Cannot stub methods on subject

### ISSUE THREAD

**Issue by postmodern** [icy-arctic-fox/spectator#33]
I'm trying to simply test when an "aliased" method simply calls another method. Instead of testing the return value, I thought I 
would use `expect(subject).to receive...`, however I receive an odd error message. Not sure whether I'm using the correct syntax?

### Example Code

```crystal
class Test
  def method2
  end

  def method1
    method2
  end
end
```

```crystal
require "./spec_helper"

Spectator.describe Test do
  describe "#method1" do
    it do
      expect(subject).to receive(:method2)

      subject.method1
    end
  end
end
```

### Actual Results

```
Failures:

  1) Test#method1 received message #method2 : Nil at spec/test_spec.cr:6 At least once with any arguments
     Failure: subject did not receive #method2 : Nil at spec/test_spec.cr:6 at least once with any arguments

       expected: At least once with any arguments
       received: 0 time(s)

```
